directories:
  output: dist-electron
  buildResources: build
appId: com.sagshub.app
productName: SagsHub
asar: false
files:
  - filter:
      - dist/**/*
      - client/dist/**/*
      - electron-standalone.cjs
      - loading.html
      - start-sagshub.bat
      - package.json
      - node_modules/**/*
      - .env
      - shared/**/*
      - server/**/*
extraResources:
  - from: start-sagshub.bat
    to: start-sagshub.bat
  - from: client/dist
    to: client/dist
  - from: .env
    to: .env
win:
  target:
    - target: portable
      arch:
        - x64
electronVersion: 36.3.1
